const express = require("express");
const config = require("config");
const users = require("../routes/users");
const auth = require("../routes/auth");
const companies = require("../routes/companies");
const shipping = require("../routes/shippings");
const products = require("../routes/products");
const s3upload = require("../routes/s3upload");
const carts = require("../routes/carts");
const productions = require("../routes/productions");
const manufacturers = require("../routes/manufacturers");
const recordDelays = require("../routes/recordDelays");
const feedback = require("../routes/feedbacks");
const card = require("../routes/cards");
const activities = require("../routes/activities");
const payments = require("../routes/payments");
const reqLogger = require("../startup/logger");
const error = require("../middleware/error");
const errorHanlder = require("../services/globalErrorHanlder");
module.exports = function (app) {
  app.use(express.json());
  app.use(express.static("public"));
  app.use(reqLogger);
  app.use("/api/users", users);
  app.use("/api/auth", auth);
  app.use("/api/company", companies);
  app.use("/api/shipping", shipping);
  app.use("/api/s3upload", s3upload);
  app.use("/api/product", products);
  app.use("/api/cart", carts);
  app.use("/api/production", productions);
  app.use("/api/manufacturer", manufacturers);
  app.use("/api/recordDelay", recordDelays);
  app.use("/api/feedback", feedback);
  app.use("/api/card", card);
  app.use("/api/activity", activities);
  app.use("/api/payments", payments);
  app.use(errorHanlder);
  app.use(error);
};
